project:
  name: quickstart-uipath-orchestrator
  parameters:
    QSS3KeyPrefix: "quickstart-uipath-orchestrator/"
    QSS3BucketName: "$[taskcat_autobucket]"
    QSS3BucketRegion: "$[taskcat_current_region]"
    HAAPassword: "$[taskcat_genpass_8]"
    OrchestratorPassword: "$[taskcat_genpass_8]"
    RDSUsername: "$[taskcat_random-string]"
    RDSPassword: "$[taskcat_genpass_8]"
    RDSDBName: "$[taskcat_random-string]"
    GatewayName: "$[taskcat_random-string]"
    HAAUser: admin@shivansh.dev
    HostedZoneID: Z03411186LX2V3ZE3N4K
    KeyPairName: sshvans
  regions:
  - ap-northeast-1
  - ap-northeast-2
  - ap-south-1
  - ap-east-1
  - ca-central-1
  - eu-central-1
  - eu-west-1
  - eu-west-2
  - eu-west-3
  - me-south-1
  - sa-east-1
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
  shorten_stack_name: true
  s3_regional_buckets: true
  package_lambda: false
tests:
  default-orchestrator:
    template: ./templates/main.template.yaml
    regions:
    - us-east-2
    parameters:
      AvailabilityZones: "$[taskcat_getaz_2]"
      UiPathFQDN: test.shivansh.dev #testone.uipathmarketplace.net

  existing-vpc:
    template: ./templates/uipath-orchestrator.template.yaml
    regions:
      - us-east-1
    parameters:
      AvailabilityZones: "$[taskcat_getaz_2]"
      UiPathFQDN: testtwo.shivansh.dev #testone.uipathmarketplace.net
      VPCCIDR: 10.0.0.0/16
      VPCID: <<vpc-id>>
      PublicSubnetID: <<public-subnet-id>>
      PrivateSubnetID: <<private-subnet-id>>
      PrivateSubnetIDs: <<subnet-id-1,subnet-id-2,subnet-id-3>>
      PublicSubnetIDs: <<subnet-id-1,subnet-id-2,subnet-id-3>>

  # three-az-orchestrator:
  #   template: ./templates/main.template.yaml
  #   regions:
  #   - us-east-1
  #   parameters:
  #     AvailabilityZones: "$[taskcat_getaz_3]"
  #     UiPathFQDN: testtwo.uipathmarketplace.net

  # add-license-orchestrator:
  #   template: ./templates/main.template.yaml
  #   regions:
  #   - us-west-1
  #   parameters:
  #     AvailabilityZones: "$[taskcat_getaz_2]"
  #     UiPathFQDN: testthree.uipathmarketplace.net
  #     OrchestratorLicense: "orchlicense"

  # europe-orchestrator:
  #   template: ./templates/main.template.yaml
  #   regions:
  #   - eu-west-1
  #   parameters:
  #     AvailabilityZones: "$[taskcat_getaz_2]"
  #     UiPathFQDN: testfour.uipathmarketplace.net
  #     OrchestratorInstanceCount: "3"
