==== Prepare your AWS account 

===== Key pair 
Make sure that at least one Amazon EC2 key pair exists in your AWS account in the Region where the Quick Start is deployed. Save the key pair name, as you need it during deployment. To create a key pair, follow the instructions in https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-key-pairs.html[Amazon EC2 key pairs and Linux instances^]. For testing or proof-of-concept purposes, we recommend creating a new key pair instead of using one that’s already being used by a production instance.

===== SSL certificate
This Quick Start requests a certificate from AWS Certificate Manager. It uses DNS certificate validation, using the DNS for the hosted zone that you have set up. If you already have a public certificate that you want to use, you can do so by providing the certificate's Amazon Resource Number (ARN).

===== Valid domain name 
This Quick Start assumes you have established ownership of the parent domain under which the web application will be served. You should have a hosted zone set up in your AWS account, with the required name server, start of authority, CNAME, and text records. For further details on how to create a public hosted zone, see https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/AboutHZWorkingWith.html[Working with public hosted zones^].

==== Prepare your {partner-company-name} account

This Quick Start uses AWS owned Amazon Machine Images (AMI). However, during the initiation of EC2 virtual machines (VMs), it downloads, installs, and configures UiPath Orchestrator and HAA. Before deployment, purchase UiPath Orchestrator and HAA add-on licenses by https://www.uipath.com/company/contact-us[contacting UiPath directly^].